controller_manager:
  ros__parameters:
    update_rate: 100

diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel: "wheel_left_joint"
    right_wheel: "wheel_right_joint"
    wheel_separation: 0.57    # distance between wheels (meters)
    wheel_radius: 0.105       # wheel radius (meters)
    cmd_vel_timeout: 0.5
    publish_rate: 50
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0, 0, 0]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0, 0, 0]
